### ISSUE TITLE
Make website mobile responsive

### ISSUE THREAD

**Issue by Naton-1** [COP4331-Group3-Fall2021/U-Ride#13]
The web front end should be tweaked to accommodate a mobile screen size.

- [ ] Splash page
- [ ] Home page
  - [ ] Search Pools modal
  - [ ] Create Pools modal

**Comment by kaylamarc** [comment]
The splash page really needs some editing. The star and car svg aren't floating correctly on smaller screens and the login box is smushing weirdly while the fields stay static.

**Comment by farnsworthe** [comment]
Site was made mobile responsive
