### ISSUE TITLE
EditPoolWindow Form Validation/Functionality

### ISSUE THREAD

**Issue by kaylamarc** [COP4331-Group3-Fall2021/U-Ride#14]
validate the form data in the edit pool window on each button click

NOTE: by unchecking a passenger, you are removing them from pool

On clicking delete:
- [x] delete pool from database
- [x] remove the card

On save:
- [x] update database with current info (could just rewrite all data even if its not different for ease?)
- [x] properly handle rider removal
- [x] update the cards with that info

Cancel button function is all set up, just closes the modal

**Comment by Naton-1** [comment]
The address fields of this form should implement Google Maps - Place Autocomplete.
