### ISSUE TITLE
SearchPoolWindow Functionality

### ISSUE THREAD

**Issue by kaylamarc** [COP4331-Group3-Fall2021/U-Ride#15]
On clicking Search:

- [ ] show the pools (cards) in the search results state

- search by driver?
- partial search?
- on empty results, show "no results" div

**** ONLY SHOW NON-FULL POOLS

**Comment by Naton-1** [comment]
The address fields of this form should implement Google Maps - Place Autocomplete.

**Comment by kaylamarc** [comment]
waiting on data to use for testing to close this
