### ISSUE TITLE
CreatePoolWindow functionality

### ISSUE THREAD

**Issue by Naton-1** [COP4331-Group3-Fall2021/U-Ride#19]
- [x] Send API call to create Carpool
- [x] Home page should be updated to reflect the newly added Carpool
- [x] Remove checkboxes
~~- [ ]Address fields of this form should implement Google Maps - Place Autocomplete~~ NOW FOR: #51  
~~- [ ] clear form on close, make sure on reopen does not show past pool [only empty fields]~~  NOW FOR: #54

**Comment by kaylamarc** [comment]
just needs places autocomplete & remove the checkboxes

**Comment by kaylamarc** [comment]
I have removed the check boxes in a different branch

**Comment by kaylamarc** [comment]
adding a task to fix how after creating& closing the modal, the data is still there
