### ISSUE TITLE
Block usage until Verify email

### ISSUE THREAD

**Issue by Landreymartin** [COP4331-Group3-Fall2021/U-Ride#22]
Need to redirect user to a verify email page when registering account. Currently allows full functionality of site upon registration.

**Comment by Landreymartin** [comment]
Is this done?

**Comment by Naton-1** [comment]
Instead of a verify email page, we can add a modal that pops up after a user registers. The modal would say something like "Please verify your email first before logging in.".

![image](https://user-images.githubusercontent.com/38639895/143922475-281b2cf6-50f3-463a-90e4-676bd5ab86aa.png)
