### ISSUE TITLE
Fix Register: It logs in upon clicking register

### ISSUE THREAD

**Issue by kaylamarc** [COP4331-Group3-Fall2021/U-Ride#35]
Upon clicking an account it auto signs in the user before verification. User should be directed to login and if they try to log in before verification they should get an error saying to verify with their email first.

**Comment by Naton-1** [comment]
- [X] User is directed to Login window after successfully registering
- [X] Login window displays unique error if user tries to login using a non-verified account (pending verification from Vic)
