### ISSUE TITLE
Fix Login: Login is broken

### ISSUE THREAD

**Issue by kaylamarc** [COP4331-Group3-Fall2021/U-Ride#36]
Trying to log in with valid and verified acount I get:
- LoginWindow.js:63 POST https://u-ride-cop4331.herokuapp.com/auth/login 400 (Bad Request)
- index.js:1 error TypeError: Cannot read properties of undefined (reading 'name')
    at LoginWindow.js:77

**Comment by Victoria-Williamson** [comment]
Closed with PR just forgot to add it
