### ISSUE TITLE
CreatePoolWindow - Clear input fields 

### ISSUE THREAD

**Issue by Naton-1** [COP4331-Group3-Fall2021/U-Ride#54]
After clicking `cancel` or submitting the form, the input fields should be cleared for the next time the user clicks `Create Pool`.

![image](https://user-images.githubusercontent.com/38639895/144168311-0d7a9ad9-7015-48ad-ab34-9afa934d6716.png)

**Comment by kaylamarc** [comment]
this will need to be done for the search pool window as well.

**Comment by Naton-1** [comment]
Completed.
