### ISSUE TITLE
dates are being converted wrong on FE

### ISSUE THREAD

**Issue by Victoria-Williamson** [COP4331-Group3-Fall2021/U-Ride#60]
Days are slightly off when being displaying dates on the card. A variation of this might fix it tho : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString

**Comment by kaylamarc** [comment]
I believe I have this fixed and figured out, will commit with #15

**Comment by kaylamarc** [comment]
should be fixed with #64
